3.9M	/mnt/skills/public
1.1M	/mnt/skills/public/docx
155K	/mnt/skills/public/docx.skill
1.5K	/mnt/skills/public/docx/LICENSE.txt
20K	/mnt/skills/public/docx/SKILL.md
1.1M	/mnt/skills/public/docx/scripts
16K	/mnt/skills/public/file-reading
6.0K	/mnt/skills/public/file-reading.skill
1.5K	/mnt/skills/public/file-reading/LICENSE.txt
14K	/mnt/skills/public/file-reading/SKILL.md
15K	/mnt/skills/public/frontend-design
6.0K	/mnt/skills/public/frontend-design.skill
10K	/mnt/skills/public/frontend-design/LICENSE.txt
4.5K	/mnt/skills/public/frontend-design/SKILL.md
60K	/mnt/skills/public/pdf
18K	/mnt/skills/public/pdf-reading
8.0K	/mnt/skills/public/pdf-reading.skill
1.5K	/mnt/skills/public/pdf-reading/LICENSE.txt
5.5K	/mnt/skills/public/pdf-reading/REFERENCE.md
11K	/mnt/skills/public/pdf-reading/SKILL.md
22K	/mnt/skills/public/pdf.skill
12K	/mnt/skills/public/pdf/FORMS.md
1.5K	/mnt/skills/public/pdf/LICENSE.txt
17K	/mnt/skills/public/pdf/REFERENCE.md
8.0K	/mnt/skills/public/pdf/SKILL.md
22K	/mnt/skills/public/pdf/scripts
1.2M	/mnt/skills/public/pptx
161K	/mnt/skills/public/pptx.skill
1.5K	/mnt/skills/public/pptx/LICENSE.txt
11K	/mnt/skills/public/pptx/SKILL.md
7.0K	/mnt/skills/public/pptx/editing.md
15K	/mnt/skills/public/pptx/pptxgenjs.md
1.1M	/mnt/skills/public/pptx/scripts
3.0K	/mnt/skills/public/product-self-knowledge
1.5K	/mnt/skills/public/product-self-knowledge.skill
3.0K	/mnt/skills/public/product-self-knowledge/SKILL.md
1.1M	/mnt/skills/public/xlsx
148K	/mnt/skills/public/xlsx.skill
1.5K	/mnt/skills/public/xlsx/LICENSE.txt
12K	/mnt/skills/public/xlsx/SKILL.md
1.1M	/mnt/skills/public/xlsx/scripts
